### PR TITLE
e2.1

### PR DESCRIPTION
**Pull request by altendky**

### CODE REVIEW

**Comment by altendky** [comment]
@jayvdb, I forgot to look at file size.  There's a 100MB limit by default on PyPI.  Are you familiar enough with macOS apps to look through the wheel and see if there are things that obviously should not be in there?  If we don't get it under 100MB I'll submit a request to get the limit increased for qt-applications.

**Comment by jayvdb** [comment]
I'll take a look in about two hours.

**Comment by jayvdb** [comment]
Nothing that I can see.
The two largest binaries are 
```
25160	qmake
152320	qdoc
```
Perhaps they could be moved to a separate package?
A `qmake` would be a mandatory dep for all of the other packages.
However `qdoc` could potentially be an optional extra package, as there are lots of uses of `qt-applications` which wouldnt need `qdoc`.

**Comment by altendky** [comment]
Thanks for the feedback.  Yeah, those two are giant for Linux as well.  I don't need \_more\_ fragmentation so I'll see if I can get an exception.  Thanks.

**Comment by altendky** [comment]
https://github.com/pypa/pypi-support/issues/1074

**Comment by altendky** [comment]
So, Qt6 on macOS is like 30% smaller...  maybe just because they are still missing a bunch of stuff?  `:]`  But, not entirely.  `qdoc` for example went from 74.2 MiB to 47.4 MiB.  `qmake` from 12.4 MiB to 5.7 MiB.  Maybe some static stuff went dynamic/shared?  Just in case this gives you any ideas to get this moving...

https://github.com/altendky/qt-applications/actions/runs/850795083
image

**Comment by jayvdb** [comment]
Is it possible to only publish to PyPI the macOS Qt versions that are under 100Mb?  I'm planning on moving to Qt 6 soon anyway, and this would just be an extra reason to do so.  I could even run most of my needs for qt-applications on Qt 6 (qmlformat, qmlscene, etc) while my app lags behind.

**Comment by altendky** [comment]
Yeah, we may end up there...  `:[`  Partial releases aren't my favorite thing, though neither is holding up progress.  Do you know what the `.a` files are?  I'm not familiar with that as a dynamically loaded file extension.  More like a thing to link against when compiling.  And qt-applications isn't exactly intended to provide an entire Qt compilation environment.  If you don't already know they are required, maybe you could try pulling them out of a wheel and seeing if things still work?

```
-rw-r--r-- 1 altendky altendky 534K May 17 18:56 libQt5AccessibilitySupport.a
-rw-r--r-- 1 altendky altendky  47M May 17 18:56 libQt5Bootstrap.a
-rw-r--r-- 1 altendky altendky 1.3M May 17 18:56 libQt5ClipboardSupport.a
-rw-r--r-- 1 altendky altendky 979K May 17 18:56 libQt5DeviceDiscoverySupport.a
-rw-r--r-- 1 altendky altendky 602K May 17 18:56 libQt5EdidSupport.a
-rw-r--r-- 1 altendky altendky 1.6M May 17 18:56 libQt5EventDispatcherSupport.a
-rw-r--r-- 1 altendky altendky 5.0M May 17 18:56 libQt5FbSupport.a
-rw-r--r-- 1 altendky altendky 5.8M May 17 18:56 libQt5FontDatabaseSupport.a
-rw-r--r-- 1 altendky altendky 685K May 17 18:56 libQt5GraphicsSupport.a
-rw-r--r-- 1 altendky altendky 2.2M May 17 18:56 libQt5OpenGLExtensions.a
-rw-r--r-- 1 altendky altendky 1.3M May 17 18:56 libQt5PacketProtocol.a
-rw-r--r-- 1 altendky altendky 2.0M May 17 18:56 libQt5PlatformCompositorSupport.a
-rw-r--r-- 1 altendky altendky  12M May 17 18:56 libQt5QmlDebug.a
-rw-r--r-- 1 altendky altendky  17M May 17 18:56 libQt5QmlDevTools.a
-rw-r--r-- 1 altendky altendky 643K May 17 18:56 libQt5ServiceSupport.a
-rw-r--r-- 1 altendky altendky  25M May 17 18:56 libQt5ThemeSupport.a
-rw-r--r-- 1 altendky altendky  22M May 17 18:56 libQt5UiTools.a
-rw-r--r-- 1 altendky altendky 3.7M May 17 18:56 libqtfreetype.a
-rw-r--r-- 1 altendky altendky 943K May 17 18:56 libqtlibpng.a
```

**Comment by jayvdb** [comment]
The .a files are needed for building Qt, so some use cases may benefit from them, but if they are not included in the Linux qt-applications then it is not desirable that they are included in the macos qt-applications.

**Comment by altendky** [comment]
Yeah, this was only intended to get the tools (Designer, Linguist, etc) for use with Python and Qt application development.  Not to fully supplant official Qt installation mechanisms when compiling Qt C++ code.  I mean, there's room for overlap, but I'll go ahead and exclude those and hopefully they are enough space to get under the limit.  I think they might.  Thanks for the quick answer.

**Comment by altendky** [comment]
good deal

image

**Comment by altendky** [comment]
Kick CI.

**Comment by altendky** [comment]
I dunno.  Can't get any builds to launch.  Guess I'll try to kill this PR and make another.  And hope...

**Comment by altendky** [comment]
Try again?

**Comment by altendky** [comment]
And again with the other one closed now.

**Comment by altendky** [comment]
Ok, so https://github.community/t/run-actions-on-pull-requests-with-merge-conflicts/17104/8 seems to suggest that in addition to the default for the checkout action to be to secretly do a merge commit and check that out so you are super confused, that is also baked down at the lowest levels such that a merge failure results in github not having _any_ workflow file to run at all.  so...  no more PRs for 'maintenance' branches.  have to enable builds on `e*` branches directly.  (and deal with occasional double builds when i forget and name a branch like `extra_stuff_that_should_only_build_on_a_pr`)

**Comment by altendky** [comment]
@jayvdb, hey look.  You got the third platform published!  `:]`  Thanks for kick starting me on this again and sticking with me for the past...  *ugh* weeks or months or whatever.  Now to roll through the other layers and then likewise for the Qt 6 stuff.

https://pypi.org/project/qt5-applications/#files

image

**Comment by altendky** [comment]
@jayvdb, do you have any time to check out the releases?  With a little luck, I've rolled either new releases or additional files for each layer and just `yourenv/bin/pip install pyqt5-tools` should work.  If it looks good to you we can close out the macOS support ticket to let people know.  Presumably there will be follow up problems, but they can be handled with isolated issues.  Then, on to rolling the Qt 6 releases.  Thanks again for your help with this.

**Comment by altendky** [comment]
Bah, I was just drafting this...  releases not up quite yet...  sorry.  In a few minutes...

**Comment by altendky** [comment]
Alrighty, `pyqt5-tools` v3.1 is up now.  https://pypi.org/project/pyqt5-tools/#files

**Comment by jayvdb** [comment]
2am here.  Tomorrow morning I will set up macOS in CI for my project which uses this on Linux only atm.

**Comment by altendky** [comment]
Heh, sure thing.  Thanks.

**Comment by jayvdb** [comment]
Ok, confirming this is working in my macos CI.

**Pull request closed without merging**
